### ISSUE TITLE
Retrieve TN earthquake data from USGS API

### ISSUE THREAD

**Issue by ocnrandolph** [nss-data-science-cohort-4/dq3-earthquakes-valkyries-dq3#14]
Key tasks:
- [x] Successfully retrieve TN earthquake data from USGS API 
- [x] Clean data (findall regex to capture all relevant incidents in Tennessee)
- [x] Start on any additional cleaning that needs to be done

Address Part 2 question 1a:
- How many earthquakes are in the dataset?

**Comment by ocnrandolph** [comment]
Here are links to some useful info for working with this dataset:
- [column descriptions] https://earthquake.usgs.gov/data/comcat/data-eventterms.php#place
- [dictonary for Flinn-Engdahl Regions] https://earthquake.usgs.gov/data/flinn_engdahl_list.php
- [magnitude, intensity, and depth] https://www.usgs.gov/natural-hazards/earthquake-hazards/science/earthquake-magnitude-energy-release-and-shaking-intensity (there's a link to this within the definitions of cdi and mmi from the column descriptions page; unfortunately it doesn't look like our dataset contains intensity info, but no problem! we can still mention it at least in passing)

**Comment by dailyp** [comment]
usgs notebook filtered to tn events.  Also looked at correlations between depth and mag, ran histograms and sorted values.  However, unable to push to either the patti_branch or main branch.   I will get with one of the tutors during Sat class to troubleshoot.

**Comment by vai2fc** [comment]
I think the USGS data is in pretty good shape and it is joinable to the base map, so can we close this issue?
